In [35]:
#Padigela Srinithya Reddy
#BL.EN.U4CSE21146

In [36]:
import math
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score, classification_report

In [37]:
df = pd.read_csv("Lab08_data.csv")
df

        Age  Income Student Credit_Rating Buys_Computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   31---40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   31---40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31---40  medium      no     excellent           yes
12  31---40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [38]:
#A1
Buys_computer_counts = df['Buys_Computer'].value_counts()

prior_prob_no = Buys_computer_counts['no'] / len(df)
prior_prob_yes = Buys_computer_counts['yes'] / len(df)

print("Prior probability of buys_computer = yes:", prior_prob_yes)
print("Prior probability of buys_computer = no:", prior_prob_no)

Prior probability of buys_computer = yes: 0.6428571428571429
Prior probability of buys_computer = no: 0.35714285714285715

In [39]:
n = len(df)
count_yes = count_no = 0
for i in range(0,n):
    if df['Buys_Computer'][i] == "yes":
        count_yes += 1
    if df['Buys_Computer'][i] == "no":
        count_no += 1
prior_prob_yes = count_yes/n
prior_prob_no = count_no/n
print("Prior probability of buys_computer = yes:", prior_prob_yes)
print("Prior probability of buys_computer = no:", prior_prob_no)

Prior probability of buys_computer = yes: 0.6428571428571429
Prior probability of buys_computer = no: 0.35714285714285715

In [40]:
#A2
feature = 'Age'


class_conditional_densities = {}
for label in df['Buys_Computer'].unique():
    class_data = df[df['Buys_Computer'] == label][feature]
    class_counts = class_data.value_counts(normalize=True).to_dict() 

    class_conditional_densities[label] = class_counts

print("Class Conditional Densities:")
for label, values in class_conditional_densities.items():
    print(f"Class {label}: {feature} probabilities: {values}")

Class Conditional Densities:
Class no: Age probabilities: {'<=30': 0.6, '>40': 0.4}
Class yes: Age probabilities: {'31---40': 0.4444444444444444, '>40': 0.3333333333333333, '<=30': 0.2222222222222222}

In [41]:
feature2 = 'Income'

class_conditional_densities = {}
for label in df['Buys_Computer'].unique():
    class_data = df[df['Buys_Computer'] == label][feature2]
    class_counts = class_data.value_counts(normalize=True).to_dict() 

    class_conditional_densities[label] = class_counts

print("Class Conditional Densities:")
for label, values in class_conditional_densities.items():
    print(f"Class {label}: {feature2} probabilities: {values}")

Class Conditional Densities:
Class no: Income probabilities: {'high': 0.4, 'medium': 0.4, 'low': 0.2}
Class yes: Income probabilities: {'medium': 0.4444444444444444, 'low': 0.3333333333333333, 'high': 0.2222222222222222}

In [42]:
feature3 = 'Student'


class_conditional_densities = {}
for label in df['Buys_Computer'].unique():
    class_data = df[df['Buys_Computer'] == label][feature3]
    class_counts = class_data.value_counts(normalize=True).to_dict() 

    class_conditional_densities[label] = class_counts

print("Class Conditional Densities:")
for label, values in class_conditional_densities.items():
    print(f"Class {label}: {feature3} probabilities: {values}")

Class Conditional Densities:
Class no: Student probabilities: {'no': 0.8, 'yes': 0.2}
Class yes: Student probabilities: {'yes': 0.6666666666666666, 'no': 0.3333333333333333}

In [43]:
feature4 = 'Credit_Rating'

class_conditional_densities = {}
for label in df['Buys_Computer'].unique():
    class_data = df[df['Buys_Computer'] == label][feature4]
    class_counts = class_data.value_counts(normalize=True).to_dict() 

    class_conditional_densities[label] = class_counts

print("Class Conditional Densities:")
for label, values in class_conditional_densities.items():
    print(f"Class {label}: {feature4} probabilities: {values}")

Class Conditional Densities:
Class no: Credit_Rating probabilities: {'excellent': 0.6, 'fair': 0.4}
Class yes: Credit_Rating probabilities: {'fair': 0.6666666666666666, 'excellent': 0.3333333333333333}

In [44]:
feature = 'Income'

class_conditional_densities = {}
for label in df['Buys_Computer'].unique():
    class_data = df[df['Buys_Computer'] == label][feature]
    class_size = len(class_data)
    
    category_counts = {}
    for category in class_data:
        if category not in category_counts:
            category_counts[category] = 1
        else:
            category_counts[category] += 1
    
    
    probabilities = {category: count / class_size for category, count in category_counts.items()}
    
    class_conditional_densities[label] = probabilities

print("Class Conditional Densities:")
for label, values in class_conditional_densities.items():
    print(f"Class {label}: {feature} probabilities: {values}")

Class Conditional Densities:
Class no: Income probabilities: {'high': 0.4, 'low': 0.2, 'medium': 0.4}
Class yes: Income probabilities: {'high': 0.2222222222222222, 'medium': 0.4444444444444444, 'low': 0.3333333333333333}

In [45]:
features = ['Age', 'Income', 'Student', 'Credit_Rating']

class_conditional_densities = {}

for feature in features:
    feature_probabilities = {}
  
    for label in df['Buys_Computer'].unique():
        class_data = df[df['Buys_Computer'] == label][feature]
        class_size = len(class_data)
        
        category_counts = {}
        for category in class_data:
            if category not in category_counts:
                category_counts[category] = 1
            else:
                category_counts[category] += 1
        
        probabilities = {category: count / class_size for category, count in category_counts.items()}
        
        feature_probabilities[label] = probabilities

    class_conditional_densities[feature] = feature_probabilities

for feature, values in class_conditional_densities.items():
    print(f"\nClass Conditional Densities for {feature}:")
    for label, probabilities in values.items():
        print(f"Class {label}: {feature} probabilities: {probabilities}")

Class Conditional Densities for Age:
Class no: Age probabilities: {'<=30': 0.6, '>40': 0.4}
Class yes: Age probabilities: {'31---40': 0.4444444444444444, '>40': 0.3333333333333333, '<=30': 0.2222222222222222}

Class Conditional Densities for Income:
Class no: Income probabilities: {'high': 0.4, 'low': 0.2, 'medium': 0.4}
Class yes: Income probabilities: {'high': 0.2222222222222222, 'medium': 0.4444444444444444, 'low': 0.3333333333333333}

Class Conditional Densities for Student:
Class no: Student probabilities: {'no': 0.8, 'yes': 0.2}
Class yes: Student probabilities: {'no': 0.3333333333333333, 'yes': 0.6666666666666666}

Class Conditional Densities for Credit_Rating:
Class no: Credit_Rating probabilities: {'fair': 0.4, 'excellent': 0.6}
Class yes: Credit_Rating probabilities: {'fair': 0.6666666666666666, 'excellent': 0.3333333333333333}

In [46]:
#A3
from scipy.stats import chi2_contingency
contg_table = pd.crosstab(index=df['Age'], columns=df['Income'])
print("Contingency Table:")
print(contg_table)

chi2, p, _, _ = chi2_contingency(contg_table)
print(f"\nChi-squared value: {chi2}")
print(f"P-value: {p}")
alpha = 0.05
print("\nSignificance Test:")
if p <= alpha:
    print("The variables are dependent.")
else:
    print("The variables are independent.")

Contingency Table:
Income   high  low  medium
Age
31---40     2    1       1
<=30        2    1       2
>40         0    2       3

Chi-squared value: 3.3249999999999997
P-value: 0.5049810026322079

Significance Test:
The variables are independent.

In [47]:
contg_table = pd.crosstab(index=df['Income'], columns=df['Student'])
print("Contingency Table:")
print(contg_table)

chi2, p, _, _ = chi2_contingency(contg_table)
print(f"\nChi-squared value: {chi2}")
print(f"P-value: {p}")
alpha = 0.05
print("\nSignificance Test:")
if p <= alpha:
    print("The variables are dependent.")
else:
    print("The variables are independent.")

Contingency Table:
Student  no  yes
Income
high      3    1
low       0    4
medium    4    2

Chi-squared value: 5.666666666666666
P-value: 0.05881647164242991

Significance Test:
The variables are independent.

In [48]:
contg_table = pd.crosstab(index=df['Student'], columns=df['Credit_Rating'])
print("Contingency Table:")
print(contg_table)

chi2, p, _, _ = chi2_contingency(contg_table)
print(f"\nChi-squared value: {chi2}")
print(f"P-value: {p}")
alpha = 0.05
print("\nSignificance Test:")
if p <= alpha:
    print("The variables are dependent.")
else:
    print("The variables are independent.")

Contingency Table:
Credit_Rating  excellent  fair
Student
no                     3     4
yes                    3     4

Chi-squared value: 0.0
P-value: 1.0

Significance Test:
The variables are independent.

In [49]:
contg_table = pd.crosstab(index=df['Age'], columns=df['Student'])
print("Contingency Table:")
print(contg_table)

chi2, p, _, _ = chi2_contingency(contg_table)
print(f"\nChi-squared value: {chi2}")
print(f"P-value: {p}")
alpha = 0.05
print("\nSignificance Test:")
if p <= alpha:
    print("The variables are dependent.")
else:
    print("The variables are independent.")

Contingency Table:
Student  no  yes
Age
31---40   2    2
<=30      3    2
>40       2    3

Chi-squared value: 0.4
P-value: 0.8187307530779818

Significance Test:
The variables are independent.

In [50]:
#A4
enc = OrdinalEncoder()
df_enc = pd.DataFrame(enc.fit_transform(df[['Age', 'Income', 'Student', 'Credit_Rating']]), columns=['Age', 'Income', 'Student', 'Credit_Rating'])
df_enc['Buys_Computer'] = df['Buys_Computer']

X = df_enc[['Age', 'Income', 'Student', 'Credit_Rating']]
y = df_enc['Buys_Computer']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

nb_clf = CategoricalNB()
nb_clf.fit(X_train, y_train)
y_pred = nb_clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.33

Classification Report:
              precision    recall  f1-score   support

          no       0.00      0.00      0.00         1
         yes       0.50      0.50      0.50         2

    accuracy                           0.33         3
   macro avg       0.25      0.25      0.25         3
weighted avg       0.33      0.33      0.33         3

In [51]:
#A5
df2 = pd.read_csv("Skin_Cancer_Metadata.csv")
df2

         lesion_id      image_id     dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male          ear
...            ...           ...    ...     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

[10015 rows x 7 columns]

In [52]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10015 entries, 0 to 10014
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lesion_id     10015 non-null  object
 1   image_id      10015 non-null  object
 2   dx            10015 non-null  object
 3   dx_type       10015 non-null  object
 4   age           9958 non-null   float64
 5   sex           10015 non-null  object
 6   localization  10015 non-null  object
dtypes: float64(1), object(6)
memory usage: 547.8+ KB

In [53]:
mean = df2['age'].mean()
df2['age'].fillna(mean, inplace = True)

In [54]:
from sklearn.preprocessing import LabelEncoder
lab_enc = LabelEncoder()
cols = ['dx_type','sex','localization']
for i in cols:
    df2[i] = lab_enc.fit_transform(df2[i])
df2

         lesion_id      image_id     dx  dx_type   age  sex  localization
0      HAM_0000118  ISIC_0027419    bkl        3  80.0    1            11
1      HAM_0000118  ISIC_0025030    bkl        3  80.0    1            11
2      HAM_0002730  ISIC_0026769    bkl        3  80.0    1            11
3      HAM_0002730  ISIC_0025661    bkl        3  80.0    1            11
4      HAM_0001466  ISIC_0031633    bkl        3  75.0    1             4
...            ...           ...    ...      ...   ...  ...           ...
10010  HAM_0002867  ISIC_0033084  akiec        3  40.0    1             0
10011  HAM_0002867  ISIC_0033550  akiec        3  40.0    1             0
10012  HAM_0002867  ISIC_0033536  akiec        3  40.0    1             0
10013  HAM_0000239  ISIC_0032854  akiec        3  80.0    1             5
10014  HAM_0003521  ISIC_0032258    mel        3  70.0    0             2

[10015 rows x 7 columns]

In [55]:
X = df2[['dx_type', 'age', 'sex', 'localization']]
y = df2['dx']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

nb_clf = CategoricalNB()
nb_clf.fit(X_train, y_train)
y_pred = nb_clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.71

Classification Report:
              precision    recall  f1-score   support

       akiec       0.20      0.01      0.03        69
         bcc       0.17      0.02      0.04        93
         bkl       0.45      0.37      0.41       228
          df       0.00      0.00      0.00        28
         mel       0.30      0.36      0.33       226
          nv       0.82      0.93      0.87      1338
        vasc       0.00      0.00      0.00        21

    accuracy                           0.71      2003
   macro avg       0.28      0.24      0.24      2003
weighted avg       0.65      0.71      0.67      2003

C:\Users\srini\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srini\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srini\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))